// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {types} from '../models';
import {config} from '../models';

export function AddRepo(arg1:main.AddRepoParams):Promise<types.AddData>;

export function AgentCleanup():Promise<main.AgentCleanupResult>;

export function AgentList():Promise<types.AgentListData>;

export function AgentReset(arg1:string):Promise<types.AgentResetData>;

export function AgentSessions():Promise<types.AgentSessionsData>;

export function ConfigGet():Promise<config.Config>;

export function ConfigSet(arg1:string,arg2:string):Promise<Record<string, any>>;

export function Greet(arg1:string):Promise<string>;

export function History(arg1:string,arg2:number):Promise<types.HistoryData>;

export function HistoryCleanup(arg1:main.HistoryCleanupReq):Promise<main.HistoryCleanupResult>;

export function IDEAddCustom(arg1:string,arg2:string):Promise<Record<string, any>>;

export function IDEDetect():Promise<Array<main.IDEInfo>>;

export function IDEGetConfig():Promise<main.IDEConfig>;

export function IDEOpen(arg1:string,arg2:string):Promise<main.IDEOpenResult>;

export function IDERemoveCustom(arg1:string):Promise<Record<string, boolean>>;

export function IDESetDefault(arg1:string):Promise<Record<string, boolean>>;

export function IsGitRepo(arg1:string):Promise<boolean>;

export function OpenDirectoryDialog():Promise<Record<string, any>>;

export function PostSyncAdd(arg1:string,arg2:main.PostSyncAddReq):Promise<types.PostSyncCommandsData>;

export function PostSyncList(arg1:string):Promise<types.PostSyncCommandsData>;

export function PostSyncRemove(arg1:string,arg2:main.PostSyncRemoveReq):Promise<types.PostSyncCommandsData>;

export function ReadAgentLog(arg1:string,arg2:string):Promise<main.AgentLogResult>;

export function RemoveRepo(arg1:string):Promise<main.RemoveResult>;

export function RepoDiff(arg1:string):Promise<main.DiffResult>;

export function Resolve(arg1:string,arg2:main.ResolveRequest):Promise<types.ResolveData>;

export function ResolveStreamStart(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function Scan(arg1:string):Promise<types.ScanData>;

export function SetAutoLaunch(arg1:boolean):Promise<Record<string, any>>;

export function SetLocale(arg1:string):Promise<Record<string, boolean>>;

export function Status(arg1:Array<string>):Promise<types.StatusData>;

export function Summarize(arg1:string,arg2:main.SummarizeReq):Promise<main.SummarizeResult>;

export function SummarizeRetry(arg1:string):Promise<main.SummarizeResult>;

export function SyncAll():Promise<types.SyncData>;

export function SyncRepo(arg1:string):Promise<types.SyncData>;
