// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRepo(arg1) {
  return window['go']['main']['App']['AddRepo'](arg1);
}

export function AgentList() {
  return window['go']['main']['App']['AgentList']();
}

export function ConfigGet() {
  return window['go']['main']['App']['ConfigGet']();
}

export function ConfigSet(arg1, arg2) {
  return window['go']['main']['App']['ConfigSet'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function History(arg1, arg2) {
  return window['go']['main']['App']['History'](arg1, arg2);
}

export function ReadAgentLog(arg1, arg2) {
  return window['go']['main']['App']['ReadAgentLog'](arg1, arg2);
}

export function RemoveRepo(arg1) {
  return window['go']['main']['App']['RemoveRepo'](arg1);
}

export function RepoDiff(arg1) {
  return window['go']['main']['App']['RepoDiff'](arg1);
}

export function Resolve(arg1, arg2) {
  return window['go']['main']['App']['Resolve'](arg1, arg2);
}

export function ResolveStreamStart(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResolveStreamStart'](arg1, arg2, arg3);
}

export function Scan(arg1) {
  return window['go']['main']['App']['Scan'](arg1);
}

export function Status(arg1) {
  return window['go']['main']['App']['Status'](arg1);
}

export function SyncAll() {
  return window['go']['main']['App']['SyncAll']();
}

export function SyncRepo(arg1) {
  return window['go']['main']['App']['SyncRepo'](arg1);
}
