// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function Greet(arg1:string):Promise<string>;

export function Status(arg1:Array<string>):Promise<types.StatusData>;
