// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRepo(arg1) {
  return window['go']['main']['App']['AddRepo'](arg1);
}

export function AgentCleanup() {
  return window['go']['main']['App']['AgentCleanup']();
}

export function AgentList() {
  return window['go']['main']['App']['AgentList']();
}

export function AgentReset(arg1) {
  return window['go']['main']['App']['AgentReset'](arg1);
}

export function AgentSessions() {
  return window['go']['main']['App']['AgentSessions']();
}

export function ConfigGet() {
  return window['go']['main']['App']['ConfigGet']();
}

export function ConfigSet(arg1, arg2) {
  return window['go']['main']['App']['ConfigSet'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function History(arg1, arg2) {
  return window['go']['main']['App']['History'](arg1, arg2);
}

export function HistoryCleanup(arg1) {
  return window['go']['main']['App']['HistoryCleanup'](arg1);
}

export function IDEAddCustom(arg1, arg2) {
  return window['go']['main']['App']['IDEAddCustom'](arg1, arg2);
}

export function IDEDetect() {
  return window['go']['main']['App']['IDEDetect']();
}

export function IDEGetConfig() {
  return window['go']['main']['App']['IDEGetConfig']();
}

export function IDEOpen(arg1, arg2) {
  return window['go']['main']['App']['IDEOpen'](arg1, arg2);
}

export function IDERemoveCustom(arg1) {
  return window['go']['main']['App']['IDERemoveCustom'](arg1);
}

export function IDESetDefault(arg1) {
  return window['go']['main']['App']['IDESetDefault'](arg1);
}

export function IsGitRepo(arg1) {
  return window['go']['main']['App']['IsGitRepo'](arg1);
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function PostSyncAdd(arg1, arg2) {
  return window['go']['main']['App']['PostSyncAdd'](arg1, arg2);
}

export function PostSyncList(arg1) {
  return window['go']['main']['App']['PostSyncList'](arg1);
}

export function PostSyncRemove(arg1, arg2) {
  return window['go']['main']['App']['PostSyncRemove'](arg1, arg2);
}

export function ReadAgentLog(arg1, arg2) {
  return window['go']['main']['App']['ReadAgentLog'](arg1, arg2);
}

export function RemoveRepo(arg1) {
  return window['go']['main']['App']['RemoveRepo'](arg1);
}

export function RepoBranches(arg1) {
  return window['go']['main']['App']['RepoBranches'](arg1);
}

export function RepoDiff(arg1) {
  return window['go']['main']['App']['RepoDiff'](arg1);
}

export function Resolve(arg1, arg2) {
  return window['go']['main']['App']['Resolve'](arg1, arg2);
}

export function ResolveStreamStart(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResolveStreamStart'](arg1, arg2, arg3);
}

export function Scan(arg1) {
  return window['go']['main']['App']['Scan'](arg1);
}

export function SetAutoLaunch(arg1) {
  return window['go']['main']['App']['SetAutoLaunch'](arg1);
}

export function SetBranchMapping(arg1) {
  return window['go']['main']['App']['SetBranchMapping'](arg1);
}

export function SetLocale(arg1) {
  return window['go']['main']['App']['SetLocale'](arg1);
}

export function Status(arg1) {
  return window['go']['main']['App']['Status'](arg1);
}

export function Summarize(arg1, arg2) {
  return window['go']['main']['App']['Summarize'](arg1, arg2);
}

export function SummarizeRetry(arg1) {
  return window['go']['main']['App']['SummarizeRetry'](arg1);
}

export function SyncAll() {
  return window['go']['main']['App']['SyncAll']();
}

export function SyncRepo(arg1) {
  return window['go']['main']['App']['SyncRepo'](arg1);
}
