// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {types} from '../models';
import {config} from '../models';

export function AddRepo(arg1:main.AddRepoParams):Promise<types.AddData>;

export function AgentList():Promise<types.AgentListData>;

export function ConfigGet():Promise<config.Config>;

export function ConfigSet(arg1:string,arg2:string):Promise<Record<string, any>>;

export function Greet(arg1:string):Promise<string>;

export function History(arg1:string,arg2:number):Promise<types.HistoryData>;

export function ReadAgentLog(arg1:string,arg2:string):Promise<main.AgentLogResult>;

export function RemoveRepo(arg1:string):Promise<main.RemoveResult>;

export function RepoDiff(arg1:string):Promise<main.DiffResult>;

export function Resolve(arg1:string,arg2:main.ResolveRequest):Promise<types.ResolveData>;

export function Scan(arg1:string):Promise<types.ScanData>;

export function Status(arg1:Array<string>):Promise<types.StatusData>;

export function SyncAll():Promise<types.SyncData>;

export function SyncRepo(arg1:string):Promise<types.SyncData>;
